### ISSUE TITLE
Assignment 2 -- Screenshots & Resources

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/MPCS51032-2019-Spring-Forum#11]
Screenshots and resource links for assignment 2 are up on the class website. As always, post questions to the forum!

**Comment by jannydiu** [comment]
Can I use segmentedControl for mybooks tab?

**Comment by susanstevens** [comment]
You should use table view sections. There's a datasource method you'll want to use called `numberOfSections(in:)`. You can return 2 from this method to get two sections in your table.

You can also use the method `tableView(_:titleForHeaderInSection:)` to set the title of each section. You can find these methods in the [UITableViewDataSource documentation](https://developer.apple.com/documentation/uikit/uitableviewdatasource).
