### ISSUE TITLE
invalid bundle id error

### ISSUE THREAD

**Issue by jannydiu** [uchicago-mobi/MPCS51032-2019-Spring-Forum#15]
I got this bundle id error but I haven't found how to fix it. Any advice?

<CKError 0x60000113f780: "Permission Failure" (10/2007); server message = "Invalid bundle ID for container"; uuid = EC897BF8-4A8C-4182-A3FF-39BCBF549DCC; container ID = "iCloud.com.MyBooks">

**Comment by susanstevens** [comment]
Are you signed into CloudKit on the device or simulator you're testing on? Are there any other lines printed above or below this error message?

**Comment by jannydiu** [comment]
I did signed into iCloud on simulator. This is the only message I got. The "uuid" is different every time I got this error. Besides I also has those remainders from XCode. I'm not sure if that matters.
![Screen Shot 2019-04-21 at 3 51 17 PM](https://user-images.githubusercontent.com/43427809/56475480-6e2a3f80-644e-11e9-9c47-9c4bf4b47f7a.png)
![Screen Shot 2019-04-21 at 3 51 54 PM](https://user-images.githubusercontent.com/43427809/56475481-708c9980-644e-11e9-8536-a0e70378ad08.png)

**Comment by susanstevens** [comment]
Try changing the bundle identifier. It looks like Xcode is complaining that your bundle identifier isn’t unique (meaning someone else has already registered it on the developer portal).

**Comment by jannydiu** [comment]
I changed the bundle identifier and then I got this error. It seems recordName is a system filed which I can't change the index to queryable.
<CKError 0x600001abb600: "Invalid Arguments" (12/2015); server message = "Field 'recordName' is not marked queryable"; uuid = D91B8102-5F22-4DFF-B6F2-EDD077D70D26; container ID = "iCloud.cocoup.MyBooks">

**Comment by jannydiu** [comment]
Never mind. I just solved it!

**Comment by susanstevens** [comment]
You should be able to add an index for `recordName`. Try going to the Indexes tab in the CloudKit Dashboard. When you click on "Add Index", you should see an option to add a "queryable" index type to `recordName`.

After you add the index, make sure you click the "Save Record Type" button in the bottom right corner.

<img width="783" alt="Screen Shot 2019-04-22 at 8 49 33 PM" src="https://user-images.githubusercontent.com/10423328/56546478-3bf90a80-6540-11e9-881b-ab3da8271028.png">
