### ISSUE TITLE
Updating CloudKit records

### ISSUE THREAD

**Issue by Celiajm** [uchicago-mobi/MPCS51032-2019-Spring-Forum#16]
I have a boolean in the saved records that records whether the book is in the read or wants to read section. I can see that the boolean is being changed when the record is being updated (from 1 to 0 and vice versa), but when this is converted back to a boolean it is always being read as false no matter whether it was saved as a 1 or a 0. Do you know what might be causing this?

**Comment by susanstevens** [comment]
How are you converting from a 1 or 0 to a boolean? My guess is that there's a bug in that logic somewhere.

Also, do you need to convert from a number to a boolean? Or could you just use 0 and 1 to represent which section of the table view the book belongs in (i.e., 0 means it belongs in the first section, 1 means it belongs in the second section)?

**Comment by Celiajm** [comment]
Yeah, I meant that I'm using the 1 and 0 to represent the boolean since CloudKIt doesn't appear to support booleans.  Then I just read the field and use an if statement on it. I've looked at the values in the CloudKit Database on the apple developer site, and the values are being stored there correctly, but even when I'm just reading them in and printing the values, they are all 0. I'm not having this issue with any of the other fields though, and they are all being downloaded correctly when I fetch the data.

**Comment by susanstevens** [comment]
Are you printing the actual `CKRecord`s? You should have some code that looks like this:

```
database.perform(query, inZoneWith: CKRecordZone.default().zoneID) { (records, error) in

} 
```
I would put `print(records)` as the very first line of that completion block. You'll get an array of objects printed to the console that look like this:

```
<CKRecord: 0x7f85acc05480; recordID=3FF74F66-38C8-437B-960B-2EB51942EE84:(_defaultZone:__defaultOwner__), recordChangeTag=jukklo10, values={
    name = "Buy groceries";
}, recordType=ToDoItem>
{
	creatorUserRecordID -> <CKRecordID: 0x60000370c200; recordName=__defaultOwner__, zoneID=_defaultZone:__defaultOwner__>
	lastModifiedUserRecordID -> <CKRecordID: 0x60000370c180; recordName=__defaultOwner__, zoneID=_defaultZone:__defaultOwner__>
	creationDate -> 2019-04-17 02:01:54 +0000
	modificationDate -> 2019-04-17 02:01:54 +0000
	modifiedByDevice -> iPhone Xs
	name -> "Buy groceries"
}
```

The part to pay attention to is "values={ name = "Buy groceries"; }". Do you see the correct numbers in the values dictionary?

If you see the correct numbers there, then you can walk through the code you have after that to see where you start getting zeros. If you _don't_ see the correct numbers there, but you _definitely_ see the correct numbers in the CloudKit Dashboard, then you've uncovered a bug in CloudKit. (But that's pretty unlikely. I just tested saving Int64 fields to CloudKit and it's working OK for me.)

**Comment by Celiajm** [comment]
Ah, okay, I found it! Thank you!
