### ISSUE TITLE
Creating New Workout Category

### ISSUE THREAD

**Issue by jarofmy** [uchicago-mobi/MPCS51032-2019-Spring-Forum#20]
Are we explicitly required to have a new view controller in order to add a new workout category? Or would we be able to accomplish the same thing by prompting an alert, where the user may enter a textfield?

**Comment by susanstevens** [comment]
You can use an alert with a textfield. I think a separate view controller is a bit more appealing visually, but as long as you provide the user some way of creating a new category, which then gets saved to Core Data, you can accomplish it however you like.

**Comment by jarofmy** [comment]
Awesome, thanks for the clarification!
