### ISSUE TITLE
INStartWorkoutIntentResponse doesn't have success

### ISSUE THREAD

**Issue by jannydiu** [uchicago-mobi/MPCS51032-2019-Spring-Forum#24]
I'am trying to start a workout through siri but it seems that there's no success respond code for INStartWorkoutIntentResponse. We could only ask siri to open our app and then start a workout manually. Is that correct? Or did I misunderstand anything important?

**Comment by jannydiu** [comment]
This is the error I got:
'success' is unavailable: INStartWorkoutIntentResponseCodeSuccess is not available to extensions. This can only be returned from the app.

**Comment by susanstevens** [comment]
Hmm... I’ll investigate and let you know what I figure out.

**Comment by jannydiu** [comment]
I found some solutions that needed to define some NSUserActivities but I'm kind of confused about the steps to define and use those NSUserActivities. If this is the solution, can you post some tutorials about how to use NSUserActivities?

**Comment by carterperrin** [comment]
I also ran into this. I have just been starting the workout from the extension before calling the completion with [`handleInApp`](https://developer.apple.com/documentation/sirikit/instartworkoutintentresponsecode/handleinapp). That seems to work, but you're still forced to open the app.

**Comment by susanstevens** [comment]
Carter’s approach sounds like the right one here. You can use this method, https://developer.apple.com/documentation/uikit/uiapplicationdelegate/2887573-application, to handle the intent in the app, without needing to pass around an NSUserActivity object.
