### ISSUE TITLE
Workout art display

### ISSUE THREAD

**Issue by jarofmy** [uchicago-mobi/MPCS51032-2019-Spring-Forum#25]
From the screen caps, there is an emoji of a biker shown, to reflect a biking workout. Are we expected to dynamically display a picture for the workouts?

Assuming a user may theoretically add any sort of workout, that does not have an emoji relevant display, such as "VO2 Max workout", or "Cross Fit" etc.

**Comment by susanstevens** [comment]
Nope! You can style the UI however you like. Images & emojis aren’t required.
