### ISSUE TITLE
SKAction scaling not working

### ISSUE THREAD

**Issue by lmnoel** [uchicago-mobi/MPCS51032-2019-Spring-Forum#27]
I have this "sliding bar" in my game, which consists of a green SKShapeNode over a red SKShapeNode (created using the GameScene editor). I am trying to animate the green bar such that it scales down to 0% width and back to 100% width repeatedly, using `SKAction.repeatForever`.

Currently, the bar is not scaling when the action is run.

Also--I want to be able to grab the current "scale" of the bar on `touchesEnded`. I think the `slider.frame.maxX` would reflect the original scaling, not the current state of scaling--am I correct? If so, what is a good way to determine the current scale?

<img width="511" alt="Screen Shot 2019-05-13 at 11 54 54" src="https://user-images.githubusercontent.com/20692394/57639634-f6939000-7575-11e9-813a-dd35c4abd2a6.png">

**Comment by susanstevens** [comment]
You could create two [scale](https://developer.apple.com/documentation/spritekit/skaction/1417699-scalex) actions, one to shrink the node to 0% and one to grow it back to 100%. Then, you could add them both to a [sequence](https://developer.apple.com/documentation/spritekit/skaction/1417817-sequence) action. Then add the sequence action to `SKAction.repeatForever`. 

I did a quick test, and it looks like `maxX` will change to reflect the scaling, so you should be able to use it to figure out the current scale.

**Comment by lmnoel** [comment]
That's just what I've done:

```
xSlider = childNode(withName: "xGreenSlider") as? SKShapeNode
        let scale = SKAction.scaleX(by: 0.1, y: 1.0, duration: 5)
        let reverseScale = scale.reversed()
        let actions = [scale, reverseScale]
        let sequence = SKAction.sequence(actions)
        xSlider?.run(SKAction.repeatForever(sequence))
```
and yet there seems to be no effect

**Comment by susanstevens** [comment]
Any chance `xSlider` is nil? Maybe the name doesn't match what's in the scene editor? Your code is working fine for me.

**Comment by lmnoel** [comment]
Ah, that was it. I was casting to SKShapeNode when in fact it was an SKSpriteNode
