### ISSUE TITLE
Get velocity just before crash

### ISSUE THREAD

**Issue by ab1470** [uchicago-mobi/MPCS51032-2019-Spring-Forum#29]
My game involves landing a spacecraft on landing pads. The landing is successful if the spacecraft touches down at a Y velocity below the threshold I set, but the spacecraft crashes if the Y velocity exceeds the threshold. 

My problem is that the app usually gives me the velocity at the exact moment that the spacecraft makes contact, rather than the moment just before (which is what I need in order to evaluate a successful landing). Usually the velocity will be something like 6.243940235133e-7 (so essentially it's giving me a velocity of 0). The exception is that when I hit the landing pad at a very high velocity, it gives me an accurate reading (something like 43.2321432). 

Do you have any ideas for how I can get the velocity immediately before touchdown?

**Comment by susanstevens** [comment]
You could try using the `update(_:)` method (https://developer.apple.com/documentation/spritekit/skscene/1519802-update). It’ll get called once per frame, before the physics simulation runs. You could have a `previousVelocity` variable on your `SKScene` that you update each time this method is called.

If just storing that one variable doesn’t prove accurate enough, you could also play around with storing an array of the last few velocities. (Maybe the velocity from five frames before the crash is the one you want, for example.)

Let me know if that helps!
