### ISSUE TITLE
persist data in document dictionary

### ISSUE THREAD

**Issue by jannydiu** [uchicago-mobi/MPCS51032-2019-Spring-Forum#3]
I noticed that out Notes app should persist data in Document Dictionary. Do you mean we need to use file system instead of user defaults by Document Dictionary?

**Comment by susanstevens** [comment]
Yes, you should save notes to the file system, not UserDefaults. The Documents Directory is one of the directories available to you in the file system.

**Comment by jannydiu** [comment]
Got it! Besides, I am planning to use textView for detailed note but I am not sure how to store or retrieve the date of the note. Any suggestions?

**Comment by susanstevens** [comment]
I would create a model object to represent each note with two properties: 1) the text of the note and 2) the last-edited date. Each time the user creates or edits a note, you can call `Date()` to get an object representing the current date.

I just posted last quarter's slides on data persistence on the course website under Session 1, so take a look there for more info on saving to the file system. The last few slides in that presentation should be helpful. Also, take a look at the WeatherApp we went over in class. It stores data to the file system as well.
