### ISSUE TITLE
Extension not appearing in simulator

### ISSUE THREAD

**Issue by Celiajm** [uchicago-mobi/MPCS51032-2019-Spring-Forum#5]
I've been having a really weird bug where for the most part, the today extension does not appear in the extension list to add to the screen in simulator. Every now and then it will seemingly randomly work and will be in the list for me to add to the screen - though it will be just an empty box. I can not even change anything between runs and it will be there one run and not the next. I've been through quite a few solutions on stack exchange and none of them have fixed the problem, has anyone else had this issue?

**Comment by susanstevens** [comment]
I'm seen this happen a few times too. One thing that's worked for me is deleting the app from the simulator and building again. If you hold down on the app icon, it'll start wiggling and then you can click the X that appears in the corner to delete it.

You could also try running your app in different simulators. Cleaning out the build folder (Product --> Clean Build Folder) never hurts either. This just wipes out any cached files and forces Xcode to re-compile everything next time you build.

Let me know if any of these suggestions help or if you're still running into the issue!

**Comment by Celiajm** [comment]
So it seems to be back for right now, but if it disappears again then I'll give these a try, but the other issue is when it hasn't disappeared it just says unable to load. I looked this up and it seems like this error comes about if the widget tries to use too much memory, but I've been getting this even if I just have a view with a label, any ideas on this?

**Comment by susanstevens** [comment]
Hmm... Are you seeing any errors in the console when this happens? A view with just a label definitely won't cause memory issues, but there could be something else preventing it from loading.

If there aren't any console errors, and if nothing seems to be wrong with your code, you might try deleting the app from the simulator just to see if that helps with the loading issue.

**Comment by Celiajm** [comment]
Hmm, so after running the debug console within the simulator, there is a sigabrt error caused by this error: 
assertion failed: 18E226: launchd_sim + 63721 [4911879E-54AD-341A-9EEA-BD6E6DDD9DD6]: 0x16

There seems to be no indicator as to what is actually causing this error. I've checked that all my outlets are hooked up right, and that doesn't seem to be the problem, so I'm not sure what this error means/ where it's coming from
