### ISSUE TITLE
BookList demo app posted

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/MPCS51032-2019-Spring-Forum#6]
There was a request for last quarter's BookList demo app, which shows how to save data to the file system and user defaults. I just posted it for anyone who wants to take a look!

**Comment by jarofmy** [comment]
The assignment prompt says to notes should be saved "to the Documents Directory".

Would it be incorrect to save data using UserDefaults?

**Comment by susanstevens** [comment]
Yes. You should save notes to the Documents Directory (using FileManager), not UserDefaults.
