### ISSUE TITLE
"Use of unresolved identifier" error

### ISSUE THREAD

**Issue by ab1470** [uchicago-mobi/MPCS51032-2019-Spring-Forum#7]
I'm getting a lot of "Use of unresolved identifier" errors with my framework. Oddly, I'm also getting these errors with the WeatherWidget sample project that I downloaded from Apple, even when I haven't changed a single line of code. 

Here's a screenshot of what's happening in the WeatherWidget project:
<img width="845" alt="Screen Shot 2019-04-10 at 1 53 18 PM" src="https://user-images.githubusercontent.com/22333279/55905636-01828b80-5b98-11e9-8f22-91e7eccac8ae.png">

I'm getting similar errors in my own project.

**Comment by Celiajm** [comment]
Import UIKit I think should fix it in your project?
